In [16]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/telco_churn.csv")

df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

In [17]:
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [18]:
# Clean column names
df.columns = df.columns.str.strip()

# Drop leakage columns as are derived after churn happens → data leakage → unrealistic model performance.
df = df.drop(columns=["Churn Score", "Churn Reason"])

# Check shape
df.shape

(7043, 31)

In [19]:
df["Churn Value"].value_counts(normalize=True)

Churn Value
0    0.73463
1    0.26537
Name: proportion, dtype: float64

In [23]:
for col in df.columns:
    print(f"'{col}'")

'Gender'
'Senior Citizen'
'Partner'
'Dependents'
'Tenure Months'
'Phone Service'
'Multiple Lines'
'Internet Service'
'Online Security'
'Online Backup'
'Device Protection'
'Tech Support'
'Streaming TV'
'Streaming Movies'
'Contract'
'Paperless Billing'
'Payment Method'
'Monthly Charges'
'Total Charges'
'Churn Label'
'Churn Value'
'CLTV'

In [24]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace("  ", " ")

In [25]:
print(df.columns.tolist())

['Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months', 'Phone Service', 'Multiple Lines', 'Internet Service', 'Online Security', 'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value', 'CLTV']

In [26]:
cols_to_drop = ["CustomerID", "Count", "Country", "State", "City",
                "Zip Code", "Lat Long", "Latitude", "Longitude"]

existing_cols = [col for col in cols_to_drop if col in df.columns]

df = df.drop(columns=existing_cols)

In [27]:
df.shape

(7043, 22)

In [28]:
df["Churn Value"].value_counts(normalize=True)

Churn Value
0    0.73463
1    0.26537
Name: proportion, dtype: float64

In [29]:
df["Total Charges"] = pd.to_numeric(df["Total Charges"], errors="coerce")
df.isnull().sum()

Gender                0
Senior Citizen        0
Partner               0
Dependents            0
Tenure Months         0
Phone Service         0
Multiple Lines        0
Internet Service      0
Online Security       0
Online Backup         0
Device Protection     0
Tech Support          0
Streaming TV          0
Streaming Movies      0
Contract              0
Paperless Billing     0
Payment Method        0
Monthly Charges       0
Total Charges        11
Churn Label           0
Churn Value           0
CLTV                  0
dtype: int64

In [30]:
df[df["Total Charges"].isnull()][["Tenure Months", "Total Charges"]]

      Tenure Months  Total Charges
2234              0            NaN
2438              0            NaN
2568              0            NaN
2667              0            NaN
2856              0            NaN
4331              0            NaN
4687              0            NaN
5104              0            NaN
5719              0            NaN
6772              0            NaN
6840              0            NaN

In [31]:
df["Total Charges"] = df["Total Charges"].fillna(0)

In [32]:
df.isnull().sum()

Gender               0
Senior Citizen       0
Partner              0
Dependents           0
Tenure Months        0
Phone Service        0
Multiple Lines       0
Internet Service     0
Online Security      0
Online Backup        0
Device Protection    0
Tech Support         0
Streaming TV         0
Streaming Movies     0
Contract             0
Paperless Billing    0
Payment Method       0
Monthly Charges      0
Total Charges        0
Churn Label          0
Churn Value          0
CLTV                 0
dtype: int64

In [33]:
df.shape
df["Churn Value"].value_counts(normalize=True)

Churn Value
0    0.73463
1    0.26537
Name: proportion, dtype: float64

In [34]:
df.groupby("Churn Value")["Tenure Months"].mean()

Churn Value
0    37.569965
1    17.979133
Name: Tenure Months, dtype: float64

In [35]:
pd.crosstab(df["Contract"], df["Churn Value"], normalize="index")

Churn Value            0         1
Contract
Month-to-month  0.572903  0.427097
One year        0.887305  0.112695
Two year        0.971681  0.028319

In [36]:
pd.crosstab(df["Tech Support"], df["Churn Value"], normalize="index")

Churn Value                 0         1
Tech Support
No                   0.583645  0.416355
No internet service  0.925950  0.074050
Yes                  0.848337  0.151663

In [37]:
df.groupby("Churn Value")["Monthly Charges"].mean()

Churn Value
0    61.265124
1    74.441332
Name: Monthly Charges, dtype: float64